
version: '3'

services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    ports:
      - 8501:8501
    command: streamlit run /src/streamlit.py # comando adicionado


  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
     - 5432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
      
volumes:
  postgres-db-volume:
