version: '3'

services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src 
    ports:
      - 8501:8501
    command: streamlit run /src/streamlit.py
    depends_on:
      - redis

  redis:
    image: redis:alpine